/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Keys;
import db.clases.Public;
import db.clases.tables.records.BitacoraCajaRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BitacoraCaja extends TableImpl<BitacoraCajaRecord> {

    private static final long serialVersionUID = 1761664556;

    /**
     * The reference instance of <code>public.bitacora_caja</code>
     */
    public static final BitacoraCaja BITACORA_CAJA = new BitacoraCaja();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BitacoraCajaRecord> getRecordType() {
        return BitacoraCajaRecord.class;
    }

    /**
     * The column <code>public.bitacora_caja.idcaja</code>.
     */
    public final TableField<BitacoraCajaRecord, Integer> IDCAJA = createField("idcaja", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.bitacora_caja.fecha</code>.
     */
    public final TableField<BitacoraCajaRecord, Timestamp> FECHA = createField("fecha", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.bitacora_caja.valor</code>.
     */
    public final TableField<BitacoraCajaRecord, BigDecimal> VALOR = createField("valor", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.bitacora_caja.empleado</code>.
     */
    public final TableField<BitacoraCajaRecord, String> EMPLEADO = createField("empleado", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.bitacora_caja.movimiento</code>.
     */
    public final TableField<BitacoraCajaRecord, String> MOVIMIENTO = createField("movimiento", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.bitacora_caja</code> table reference
     */
    public BitacoraCaja() {
        this("bitacora_caja", null);
    }

    /**
     * Create an aliased <code>public.bitacora_caja</code> table reference
     */
    public BitacoraCaja(String alias) {
        this(alias, BITACORA_CAJA);
    }

    private BitacoraCaja(String alias, Table<BitacoraCajaRecord> aliased) {
        this(alias, aliased, null);
    }

    private BitacoraCaja(String alias, Table<BitacoraCajaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<BitacoraCajaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<BitacoraCajaRecord, ?>>asList(Keys.BITACORA_CAJA__FK_BITACORA_CAJA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BitacoraCaja as(String alias) {
        return new BitacoraCaja(alias, this);
    }

    /**
     * Rename this table
     */
    public BitacoraCaja rename(String name) {
        return new BitacoraCaja(name, null);
    }
}
