/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Keys;
import db.clases.Public;
import db.clases.tables.records.CategoriaInventarioRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoriaInventario extends TableImpl<CategoriaInventarioRecord> {

    private static final long serialVersionUID = -214224609;

    /**
     * The reference instance of <code>public.categoria_inventario</code>
     */
    public static final CategoriaInventario CATEGORIA_INVENTARIO = new CategoriaInventario();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CategoriaInventarioRecord> getRecordType() {
        return CategoriaInventarioRecord.class;
    }

    /**
     * The column <code>public.categoria_inventario.idcategoria</code>.
     */
    public final TableField<CategoriaInventarioRecord, Integer> IDCATEGORIA = createField("idcategoria", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval(('\"categoria_inventario_idcategoria_seq\"'::text)::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.categoria_inventario.nombre</code>.
     */
    public final TableField<CategoriaInventarioRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.categoria_inventario.descripcion</code>.
     */
    public final TableField<CategoriaInventarioRecord, String> DESCRIPCION = createField("descripcion", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.categoria_inventario</code> table reference
     */
    public CategoriaInventario() {
        this("categoria_inventario", null);
    }

    /**
     * Create an aliased <code>public.categoria_inventario</code> table reference
     */
    public CategoriaInventario(String alias) {
        this(alias, CATEGORIA_INVENTARIO);
    }

    private CategoriaInventario(String alias, Table<CategoriaInventarioRecord> aliased) {
        this(alias, aliased, null);
    }

    private CategoriaInventario(String alias, Table<CategoriaInventarioRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CategoriaInventarioRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CATEGORIA_INVENTARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CategoriaInventarioRecord> getPrimaryKey() {
        return Keys.PK_CATEGORIA_INVENTARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CategoriaInventarioRecord>> getKeys() {
        return Arrays.<UniqueKey<CategoriaInventarioRecord>>asList(Keys.PK_CATEGORIA_INVENTARIO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoriaInventario as(String alias) {
        return new CategoriaInventario(alias, this);
    }

    /**
     * Rename this table
     */
    public CategoriaInventario rename(String name) {
        return new CategoriaInventario(name, null);
    }
}
