/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Keys;
import db.clases.Public;
import db.clases.tables.records.DetalleCotizacionRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DetalleCotizacion extends TableImpl<DetalleCotizacionRecord> {

    private static final long serialVersionUID = 2067780903;

    /**
     * The reference instance of <code>public.detalle_cotizacion</code>
     */
    public static final DetalleCotizacion DETALLE_COTIZACION = new DetalleCotizacion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DetalleCotizacionRecord> getRecordType() {
        return DetalleCotizacionRecord.class;
    }

    /**
     * The column <code>public.detalle_cotizacion.cantidad</code>.
     */
    public final TableField<DetalleCotizacionRecord, Float> CANTIDAD = createField("cantidad", org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * The column <code>public.detalle_cotizacion.precio</code>.
     */
    public final TableField<DetalleCotizacionRecord, BigDecimal> PRECIO = createField("precio", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.detalle_cotizacion.idtamanio</code>.
     */
    public final TableField<DetalleCotizacionRecord, Integer> IDTAMANIO = createField("idtamanio", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.detalle_cotizacion.idcotizacion</code>.
     */
    public final TableField<DetalleCotizacionRecord, Integer> IDCOTIZACION = createField("idcotizacion", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.detalle_cotizacion.idproducto</code>.
     */
    public final TableField<DetalleCotizacionRecord, Integer> IDPRODUCTO = createField("idproducto", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.detalle_cotizacion.especial</code>.
     */
    public final TableField<DetalleCotizacionRecord, Boolean> ESPECIAL = createField("especial", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.detalle_cotizacion.ancho</code>.
     */
    public final TableField<DetalleCotizacionRecord, Float> ANCHO = createField("ancho", org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * The column <code>public.detalle_cotizacion.largo</code>.
     */
    public final TableField<DetalleCotizacionRecord, Float> LARGO = createField("largo", org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * Create a <code>public.detalle_cotizacion</code> table reference
     */
    public DetalleCotizacion() {
        this("detalle_cotizacion", null);
    }

    /**
     * Create an aliased <code>public.detalle_cotizacion</code> table reference
     */
    public DetalleCotizacion(String alias) {
        this(alias, DETALLE_COTIZACION);
    }

    private DetalleCotizacion(String alias, Table<DetalleCotizacionRecord> aliased) {
        this(alias, aliased, null);
    }

    private DetalleCotizacion(String alias, Table<DetalleCotizacionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DetalleCotizacionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DetalleCotizacionRecord, ?>>asList(Keys.DETALLE_COTIZACION__FK_DETALLE_COTIZACION_TAMANIO, Keys.DETALLE_COTIZACION__FK_DETALLE_COTIZACION_COTIZACION, Keys.DETALLE_COTIZACION__FK_DETALLE_COTIZACION_PRODUCTO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DetalleCotizacion as(String alias) {
        return new DetalleCotizacion(alias, this);
    }

    /**
     * Rename this table
     */
    public DetalleCotizacion rename(String name) {
        return new DetalleCotizacion(name, null);
    }
}
