/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Keys;
import db.clases.Public;
import db.clases.tables.records.ModuloRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Modulo extends TableImpl<ModuloRecord> {

    private static final long serialVersionUID = 1344469530;

    /**
     * The reference instance of <code>public.modulo</code>
     */
    public static final Modulo MODULO = new Modulo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ModuloRecord> getRecordType() {
        return ModuloRecord.class;
    }

    /**
     * The column <code>public.modulo.idrol</code>.
     */
    public final TableField<ModuloRecord, Integer> IDROL = createField("idrol", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval(('\"rol_idrol_seq\"'::text)::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.modulo.modulo</code>.
     */
    public final TableField<ModuloRecord, String> MODULO_ = createField("modulo", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.modulo</code> table reference
     */
    public Modulo() {
        this("modulo", null);
    }

    /**
     * Create an aliased <code>public.modulo</code> table reference
     */
    public Modulo(String alias) {
        this(alias, MODULO);
    }

    private Modulo(String alias, Table<ModuloRecord> aliased) {
        this(alias, aliased, null);
    }

    private Modulo(String alias, Table<ModuloRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ModuloRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MODULO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ModuloRecord> getPrimaryKey() {
        return Keys.PK_ROL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ModuloRecord>> getKeys() {
        return Arrays.<UniqueKey<ModuloRecord>>asList(Keys.PK_ROL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Modulo as(String alias) {
        return new Modulo(alias, this);
    }

    /**
     * Rename this table
     */
    public Modulo rename(String name) {
        return new Modulo(name, null);
    }
}
