/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Public;
import db.clases.tables.records.MovimientoCajaRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovimientoCaja extends TableImpl<MovimientoCajaRecord> {

    private static final long serialVersionUID = 1808211231;

    /**
     * The reference instance of <code>public.movimiento_caja</code>
     */
    public static final MovimientoCaja MOVIMIENTO_CAJA = new MovimientoCaja();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MovimientoCajaRecord> getRecordType() {
        return MovimientoCajaRecord.class;
    }

    /**
     * The column <code>public.movimiento_caja.idcaja</code>.
     */
    public final TableField<MovimientoCajaRecord, Integer> IDCAJA = createField("idcaja", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.movimiento_caja.apertura</code>.
     */
    public final TableField<MovimientoCajaRecord, Timestamp> APERTURA = createField("apertura", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.movimiento_caja.cierre</code>.
     */
    public final TableField<MovimientoCajaRecord, Timestamp> CIERRE = createField("cierre", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.movimiento_caja</code> table reference
     */
    public MovimientoCaja() {
        this("movimiento_caja", null);
    }

    /**
     * Create an aliased <code>public.movimiento_caja</code> table reference
     */
    public MovimientoCaja(String alias) {
        this(alias, MOVIMIENTO_CAJA);
    }

    private MovimientoCaja(String alias, Table<MovimientoCajaRecord> aliased) {
        this(alias, aliased, null);
    }

    private MovimientoCaja(String alias, Table<MovimientoCajaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovimientoCaja as(String alias) {
        return new MovimientoCaja(alias, this);
    }

    /**
     * Rename this table
     */
    public MovimientoCaja rename(String name) {
        return new MovimientoCaja(name, null);
    }
}
