/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Keys;
import db.clases.Public;
import db.clases.tables.records.PagosPedidoRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PagosPedido extends TableImpl<PagosPedidoRecord> {

    private static final long serialVersionUID = 1837094240;

    /**
     * The reference instance of <code>public.pagos_pedido</code>
     */
    public static final PagosPedido PAGOS_PEDIDO = new PagosPedido();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PagosPedidoRecord> getRecordType() {
        return PagosPedidoRecord.class;
    }

    /**
     * The column <code>public.pagos_pedido.pago</code>.
     */
    public final TableField<PagosPedidoRecord, BigDecimal> PAGO = createField("pago", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.pagos_pedido.fecha</code>.
     */
    public final TableField<PagosPedidoRecord, Date> FECHA = createField("fecha", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.pagos_pedido.idpedido</code>.
     */
    public final TableField<PagosPedidoRecord, Integer> IDPEDIDO = createField("idpedido", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.pagos_pedido</code> table reference
     */
    public PagosPedido() {
        this("pagos_pedido", null);
    }

    /**
     * Create an aliased <code>public.pagos_pedido</code> table reference
     */
    public PagosPedido(String alias) {
        this(alias, PAGOS_PEDIDO);
    }

    private PagosPedido(String alias, Table<PagosPedidoRecord> aliased) {
        this(alias, aliased, null);
    }

    private PagosPedido(String alias, Table<PagosPedidoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PagosPedidoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PagosPedidoRecord, ?>>asList(Keys.PAGOS_PEDIDO__FK_PAGOS_PEDIDO_PEDIDO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PagosPedido as(String alias) {
        return new PagosPedido(alias, this);
    }

    /**
     * Rename this table
     */
    public PagosPedido rename(String name) {
        return new PagosPedido(name, null);
    }
}
