/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Public;
import db.clases.tables.records.VAsociadoRecetaRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VAsociadoReceta extends TableImpl<VAsociadoRecetaRecord> {

    private static final long serialVersionUID = 1849830164;

    /**
     * The reference instance of <code>public.v_asociado_receta</code>
     */
    public static final VAsociadoReceta V_ASOCIADO_RECETA = new VAsociadoReceta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VAsociadoRecetaRecord> getRecordType() {
        return VAsociadoRecetaRecord.class;
    }

    /**
     * The column <code>public.v_asociado_receta.idinventario</code>.
     */
    public final TableField<VAsociadoRecetaRecord, Integer> IDINVENTARIO = createField("idinventario", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_asociado_receta.idproducto</code>.
     */
    public final TableField<VAsociadoRecetaRecord, Integer> IDPRODUCTO = createField("idproducto", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_asociado_receta.codigo</code>.
     */
    public final TableField<VAsociadoRecetaRecord, String> CODIGO = createField("codigo", org.jooq.impl.SQLDataType.VARCHAR.length(7), this, "");

    /**
     * The column <code>public.v_asociado_receta.nombre</code>.
     */
    public final TableField<VAsociadoRecetaRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.v_asociado_receta</code> table reference
     */
    public VAsociadoReceta() {
        this("v_asociado_receta", null);
    }

    /**
     * Create an aliased <code>public.v_asociado_receta</code> table reference
     */
    public VAsociadoReceta(String alias) {
        this(alias, V_ASOCIADO_RECETA);
    }

    private VAsociadoReceta(String alias, Table<VAsociadoRecetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private VAsociadoReceta(String alias, Table<VAsociadoRecetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAsociadoReceta as(String alias) {
        return new VAsociadoReceta(alias, this);
    }

    /**
     * Rename this table
     */
    public VAsociadoReceta rename(String name) {
        return new VAsociadoReceta(name, null);
    }
}
