/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Public;
import db.clases.tables.records.VCajaMovimientoRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VCajaMovimiento extends TableImpl<VCajaMovimientoRecord> {

    private static final long serialVersionUID = -758875722;

    /**
     * The reference instance of <code>public.v_caja_movimiento</code>
     */
    public static final VCajaMovimiento V_CAJA_MOVIMIENTO = new VCajaMovimiento();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VCajaMovimientoRecord> getRecordType() {
        return VCajaMovimientoRecord.class;
    }

    /**
     * The column <code>public.v_caja_movimiento.idcaja</code>.
     */
    public final TableField<VCajaMovimientoRecord, Integer> IDCAJA = createField("idcaja", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_caja_movimiento.ipcaja</code>.
     */
    public final TableField<VCajaMovimientoRecord, String> IPCAJA = createField("ipcaja", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_caja_movimiento.estado</code>.
     */
    public final TableField<VCajaMovimientoRecord, Boolean> ESTADO = createField("estado", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_caja_movimiento.detalle</code>.
     */
    public final TableField<VCajaMovimientoRecord, String> DETALLE = createField("detalle", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_caja_movimiento.baja</code>.
     */
    public final TableField<VCajaMovimientoRecord, Boolean> BAJA = createField("baja", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_caja_movimiento.fecha</code>.
     */
    public final TableField<VCajaMovimientoRecord, Timestamp> FECHA = createField("fecha", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_caja_movimiento.valor</code>.
     */
    public final TableField<VCajaMovimientoRecord, BigDecimal> VALOR = createField("valor", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.v_caja_movimiento.empleado</code>.
     */
    public final TableField<VCajaMovimientoRecord, String> EMPLEADO = createField("empleado", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_caja_movimiento.movimiento</code>.
     */
    public final TableField<VCajaMovimientoRecord, String> MOVIMIENTO = createField("movimiento", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.v_caja_movimiento</code> table reference
     */
    public VCajaMovimiento() {
        this("v_caja_movimiento", null);
    }

    /**
     * Create an aliased <code>public.v_caja_movimiento</code> table reference
     */
    public VCajaMovimiento(String alias) {
        this(alias, V_CAJA_MOVIMIENTO);
    }

    private VCajaMovimiento(String alias, Table<VCajaMovimientoRecord> aliased) {
        this(alias, aliased, null);
    }

    private VCajaMovimiento(String alias, Table<VCajaMovimientoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCajaMovimiento as(String alias) {
        return new VCajaMovimiento(alias, this);
    }

    /**
     * Rename this table
     */
    public VCajaMovimiento rename(String name) {
        return new VCajaMovimiento(name, null);
    }
}
