/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Public;
import db.clases.tables.records.VClientesRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VClientes extends TableImpl<VClientesRecord> {

    private static final long serialVersionUID = 1915024657;

    /**
     * The reference instance of <code>public.v_clientes</code>
     */
    public static final VClientes V_CLIENTES = new VClientes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VClientesRecord> getRecordType() {
        return VClientesRecord.class;
    }

    /**
     * The column <code>public.v_clientes.idcliente</code>.
     */
    public final TableField<VClientesRecord, Integer> IDCLIENTE = createField("idcliente", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_clientes.nombre</code>.
     */
    public final TableField<VClientesRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_clientes.direccion</code>.
     */
    public final TableField<VClientesRecord, String> DIRECCION = createField("direccion", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_clientes.telefono</code>.
     */
    public final TableField<VClientesRecord, String> TELEFONO = createField("telefono", org.jooq.impl.SQLDataType.VARCHAR.length(9), this, "");

    /**
     * The column <code>public.v_clientes.tipo</code>.
     */
    public final TableField<VClientesRecord, String> TIPO = createField("tipo", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_clientes.categoria</code>.
     */
    public final TableField<VClientesRecord, String> CATEGORIA = createField("categoria", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_clientes.baja</code>.
     */
    public final TableField<VClientesRecord, Boolean> BAJA = createField("baja", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>public.v_clientes</code> table reference
     */
    public VClientes() {
        this("v_clientes", null);
    }

    /**
     * Create an aliased <code>public.v_clientes</code> table reference
     */
    public VClientes(String alias) {
        this(alias, V_CLIENTES);
    }

    private VClientes(String alias, Table<VClientesRecord> aliased) {
        this(alias, aliased, null);
    }

    private VClientes(String alias, Table<VClientesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VClientes as(String alias) {
        return new VClientes(alias, this);
    }

    /**
     * Rename this table
     */
    public VClientes rename(String name) {
        return new VClientes(name, null);
    }
}
