/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Public;
import db.clases.tables.records.VConsumfinalRecord;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VConsumfinal extends TableImpl<VConsumfinalRecord> {

    private static final long serialVersionUID = -273262417;

    /**
     * The reference instance of <code>public.v_consumfinal</code>
     */
    public static final VConsumfinal V_CONSUMFINAL = new VConsumfinal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VConsumfinalRecord> getRecordType() {
        return VConsumfinalRecord.class;
    }

    /**
     * The column <code>public.v_consumfinal.idventa</code>.
     */
    public final TableField<VConsumfinalRecord, Integer> IDVENTA = createField("idventa", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_consumfinal.numerofactura</code>.
     */
    public final TableField<VConsumfinalRecord, String> NUMEROFACTURA = createField("numerofactura", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_consumfinal.fecha</code>.
     */
    public final TableField<VConsumfinalRecord, Date> FECHA = createField("fecha", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.v_consumfinal.nombre</code>.
     */
    public final TableField<VConsumfinalRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_consumfinal.direccion</code>.
     */
    public final TableField<VConsumfinalRecord, String> DIRECCION = createField("direccion", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_consumfinal.ventatotal</code>.
     */
    public final TableField<VConsumfinalRecord, BigDecimal> VENTATOTAL = createField("ventatotal", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.v_consumfinal.enletras</code>.
     */
    public final TableField<VConsumfinalRecord, String> ENLETRAS = createField("enletras", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.v_consumfinal</code> table reference
     */
    public VConsumfinal() {
        this("v_consumfinal", null);
    }

    /**
     * Create an aliased <code>public.v_consumfinal</code> table reference
     */
    public VConsumfinal(String alias) {
        this(alias, V_CONSUMFINAL);
    }

    private VConsumfinal(String alias, Table<VConsumfinalRecord> aliased) {
        this(alias, aliased, null);
    }

    private VConsumfinal(String alias, Table<VConsumfinalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VConsumfinal as(String alias) {
        return new VConsumfinal(alias, this);
    }

    /**
     * Rename this table
     */
    public VConsumfinal rename(String name) {
        return new VConsumfinal(name, null);
    }
}
