/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Public;
import db.clases.tables.records.VCotizacionRecord;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VCotizacion extends TableImpl<VCotizacionRecord> {

    private static final long serialVersionUID = 1501637837;

    /**
     * The reference instance of <code>public.v_cotizacion</code>
     */
    public static final VCotizacion V_COTIZACION = new VCotizacion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VCotizacionRecord> getRecordType() {
        return VCotizacionRecord.class;
    }

    /**
     * The column <code>public.v_cotizacion.idcotizacion</code>.
     */
    public final TableField<VCotizacionRecord, Integer> IDCOTIZACION = createField("idcotizacion", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_cotizacion.numero</code>.
     */
    public final TableField<VCotizacionRecord, String> NUMERO = createField("numero", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

    /**
     * The column <code>public.v_cotizacion.fecha</code>.
     */
    public final TableField<VCotizacionRecord, Date> FECHA = createField("fecha", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.v_cotizacion.idcliente</code>.
     */
    public final TableField<VCotizacionRecord, Integer> IDCLIENTE = createField("idcliente", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_cotizacion.nombrecliente</code>.
     */
    public final TableField<VCotizacionRecord, String> NOMBRECLIENTE = createField("nombrecliente", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_cotizacion.direccion</code>.
     */
    public final TableField<VCotizacionRecord, String> DIRECCION = createField("direccion", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_cotizacion.telefono</code>.
     */
    public final TableField<VCotizacionRecord, String> TELEFONO = createField("telefono", org.jooq.impl.SQLDataType.VARCHAR.length(9), this, "");

    /**
     * The column <code>public.v_cotizacion.total</code>.
     */
    public final TableField<VCotizacionRecord, BigDecimal> TOTAL = createField("total", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.v_cotizacion.enletras</code>.
     */
    public final TableField<VCotizacionRecord, String> ENLETRAS = createField("enletras", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_cotizacion.validapor</code>.
     */
    public final TableField<VCotizacionRecord, Integer> VALIDAPOR = createField("validapor", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_cotizacion.propietario</code>.
     */
    public final TableField<VCotizacionRecord, String> PROPIETARIO = createField("propietario", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_cotizacion.firma</code>.
     */
    public final TableField<VCotizacionRecord, byte[]> FIRMA = createField("firma", org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.v_cotizacion.sello</code>.
     */
    public final TableField<VCotizacionRecord, byte[]> SELLO = createField("sello", org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.v_cotizacion.vencimiento</code>.
     */
    public final TableField<VCotizacionRecord, Date> VENCIMIENTO = createField("vencimiento", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.v_cotizacion.case</code>.
     */
    public final TableField<VCotizacionRecord, String> CASE = createField("case", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.v_cotizacion</code> table reference
     */
    public VCotizacion() {
        this("v_cotizacion", null);
    }

    /**
     * Create an aliased <code>public.v_cotizacion</code> table reference
     */
    public VCotizacion(String alias) {
        this(alias, V_COTIZACION);
    }

    private VCotizacion(String alias, Table<VCotizacionRecord> aliased) {
        this(alias, aliased, null);
    }

    private VCotizacion(String alias, Table<VCotizacionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCotizacion as(String alias) {
        return new VCotizacion(alias, this);
    }

    /**
     * Rename this table
     */
    public VCotizacion rename(String name) {
        return new VCotizacion(name, null);
    }
}
