/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Public;
import db.clases.tables.records.VCredfiscalRecord;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VCredfiscal extends TableImpl<VCredfiscalRecord> {

    private static final long serialVersionUID = -1977336618;

    /**
     * The reference instance of <code>public.v_credfiscal</code>
     */
    public static final VCredfiscal V_CREDFISCAL = new VCredfiscal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VCredfiscalRecord> getRecordType() {
        return VCredfiscalRecord.class;
    }

    /**
     * The column <code>public.v_credfiscal.nombre</code>.
     */
    public final TableField<VCredfiscalRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_credfiscal.direccion</code>.
     */
    public final TableField<VCredfiscalRecord, String> DIRECCION = createField("direccion", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_credfiscal.nit</code>.
     */
    public final TableField<VCredfiscalRecord, String> NIT = createField("nit", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.v_credfiscal.numregistro</code>.
     */
    public final TableField<VCredfiscalRecord, String> NUMREGISTRO = createField("numregistro", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.v_credfiscal.giro</code>.
     */
    public final TableField<VCredfiscalRecord, String> GIRO = createField("giro", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_credfiscal.numerofactura</code>.
     */
    public final TableField<VCredfiscalRecord, String> NUMEROFACTURA = createField("numerofactura", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_credfiscal.fecha</code>.
     */
    public final TableField<VCredfiscalRecord, Date> FECHA = createField("fecha", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.v_credfiscal.sumas</code>.
     */
    public final TableField<VCredfiscalRecord, BigDecimal> SUMAS = createField("sumas", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.v_credfiscal.iva</code>.
     */
    public final TableField<VCredfiscalRecord, BigDecimal> IVA = createField("iva", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.v_credfiscal.ventatotal</code>.
     */
    public final TableField<VCredfiscalRecord, BigDecimal> VENTATOTAL = createField("ventatotal", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.v_credfiscal.enletras</code>.
     */
    public final TableField<VCredfiscalRecord, String> ENLETRAS = createField("enletras", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_credfiscal.idventa</code>.
     */
    public final TableField<VCredfiscalRecord, Integer> IDVENTA = createField("idventa", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_credfiscal.idpedido</code>.
     */
    public final TableField<VCredfiscalRecord, Integer> IDPEDIDO = createField("idpedido", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_credfiscal.numeropedido</code>.
     */
    public final TableField<VCredfiscalRecord, String> NUMEROPEDIDO = createField("numeropedido", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

    /**
     * Create a <code>public.v_credfiscal</code> table reference
     */
    public VCredfiscal() {
        this("v_credfiscal", null);
    }

    /**
     * Create an aliased <code>public.v_credfiscal</code> table reference
     */
    public VCredfiscal(String alias) {
        this(alias, V_CREDFISCAL);
    }

    private VCredfiscal(String alias, Table<VCredfiscalRecord> aliased) {
        this(alias, aliased, null);
    }

    private VCredfiscal(String alias, Table<VCredfiscalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCredfiscal as(String alias) {
        return new VCredfiscal(alias, this);
    }

    /**
     * Rename this table
     */
    public VCredfiscal rename(String name) {
        return new VCredfiscal(name, null);
    }
}
