/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Public;
import db.clases.tables.records.VDetalleCotizacionRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VDetalleCotizacion extends TableImpl<VDetalleCotizacionRecord> {

    private static final long serialVersionUID = 318620154;

    /**
     * The reference instance of <code>public.v_detalle_cotizacion</code>
     */
    public static final VDetalleCotizacion V_DETALLE_COTIZACION = new VDetalleCotizacion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VDetalleCotizacionRecord> getRecordType() {
        return VDetalleCotizacionRecord.class;
    }

    /**
     * The column <code>public.v_detalle_cotizacion.idcotizacion</code>.
     */
    public final TableField<VDetalleCotizacionRecord, Integer> IDCOTIZACION = createField("idcotizacion", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_detalle_cotizacion.numero</code>.
     */
    public final TableField<VDetalleCotizacionRecord, String> NUMERO = createField("numero", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

    /**
     * The column <code>public.v_detalle_cotizacion.idproducto</code>.
     */
    public final TableField<VDetalleCotizacionRecord, Integer> IDPRODUCTO = createField("idproducto", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_detalle_cotizacion.codigo</code>.
     */
    public final TableField<VDetalleCotizacionRecord, String> CODIGO = createField("codigo", org.jooq.impl.SQLDataType.VARCHAR.length(7), this, "");

    /**
     * The column <code>public.v_detalle_cotizacion.nombre</code>.
     */
    public final TableField<VDetalleCotizacionRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_detalle_cotizacion.ancho</code>.
     */
    public final TableField<VDetalleCotizacionRecord, Float> ANCHO = createField("ancho", org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * The column <code>public.v_detalle_cotizacion.largo</code>.
     */
    public final TableField<VDetalleCotizacionRecord, Float> LARGO = createField("largo", org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * The column <code>public.v_detalle_cotizacion.especial</code>.
     */
    public final TableField<VDetalleCotizacionRecord, Boolean> ESPECIAL = createField("especial", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_detalle_cotizacion.cantidad</code>.
     */
    public final TableField<VDetalleCotizacionRecord, Float> CANTIDAD = createField("cantidad", org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * The column <code>public.v_detalle_cotizacion.precio</code>.
     */
    public final TableField<VDetalleCotizacionRecord, BigDecimal> PRECIO = createField("precio", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.v_detalle_cotizacion.subtotal</code>.
     */
    public final TableField<VDetalleCotizacionRecord, BigDecimal> SUBTOTAL = createField("subtotal", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.v_detalle_cotizacion.tamanio</code>.
     */
    public final TableField<VDetalleCotizacionRecord, String> TAMANIO = createField("tamanio", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_detalle_cotizacion.idtamanio</code>.
     */
    public final TableField<VDetalleCotizacionRecord, Integer> IDTAMANIO = createField("idtamanio", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.v_detalle_cotizacion</code> table reference
     */
    public VDetalleCotizacion() {
        this("v_detalle_cotizacion", null);
    }

    /**
     * Create an aliased <code>public.v_detalle_cotizacion</code> table reference
     */
    public VDetalleCotizacion(String alias) {
        this(alias, V_DETALLE_COTIZACION);
    }

    private VDetalleCotizacion(String alias, Table<VDetalleCotizacionRecord> aliased) {
        this(alias, aliased, null);
    }

    private VDetalleCotizacion(String alias, Table<VDetalleCotizacionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacion as(String alias) {
        return new VDetalleCotizacion(alias, this);
    }

    /**
     * Rename this table
     */
    public VDetalleCotizacion rename(String name) {
        return new VDetalleCotizacion(name, null);
    }
}
