/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Public;
import db.clases.tables.records.VDetallePedidoRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VDetallePedido extends TableImpl<VDetallePedidoRecord> {

    private static final long serialVersionUID = -1562483118;

    /**
     * The reference instance of <code>public.v_detalle_pedido</code>
     */
    public static final VDetallePedido V_DETALLE_PEDIDO = new VDetallePedido();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VDetallePedidoRecord> getRecordType() {
        return VDetallePedidoRecord.class;
    }

    /**
     * The column <code>public.v_detalle_pedido.idpedido</code>.
     */
    public final TableField<VDetallePedidoRecord, Integer> IDPEDIDO = createField("idpedido", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_detalle_pedido.numero</code>.
     */
    public final TableField<VDetallePedidoRecord, String> NUMERO = createField("numero", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

    /**
     * The column <code>public.v_detalle_pedido.nombre</code>.
     */
    public final TableField<VDetallePedidoRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_detalle_pedido.cantidad</code>.
     */
    public final TableField<VDetallePedidoRecord, Float> CANTIDAD = createField("cantidad", org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * The column <code>public.v_detalle_pedido.precio</code>.
     */
    public final TableField<VDetallePedidoRecord, BigDecimal> PRECIO = createField("precio", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.v_detalle_pedido.subtotal</code>.
     */
    public final TableField<VDetallePedidoRecord, BigDecimal> SUBTOTAL = createField("subtotal", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.v_detalle_pedido.tamanio</code>.
     */
    public final TableField<VDetallePedidoRecord, String> TAMANIO = createField("tamanio", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.v_detalle_pedido</code> table reference
     */
    public VDetallePedido() {
        this("v_detalle_pedido", null);
    }

    /**
     * Create an aliased <code>public.v_detalle_pedido</code> table reference
     */
    public VDetallePedido(String alias) {
        this(alias, V_DETALLE_PEDIDO);
    }

    private VDetallePedido(String alias, Table<VDetallePedidoRecord> aliased) {
        this(alias, aliased, null);
    }

    private VDetallePedido(String alias, Table<VDetallePedidoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetallePedido as(String alias) {
        return new VDetallePedido(alias, this);
    }

    /**
     * Rename this table
     */
    public VDetallePedido rename(String name) {
        return new VDetallePedido(name, null);
    }
}
