/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Public;
import db.clases.tables.records.VMedidasRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VMedidas extends TableImpl<VMedidasRecord> {

    private static final long serialVersionUID = -1225697211;

    /**
     * The reference instance of <code>public.v_medidas</code>
     */
    public static final VMedidas V_MEDIDAS = new VMedidas();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VMedidasRecord> getRecordType() {
        return VMedidasRecord.class;
    }

    /**
     * The column <code>public.v_medidas.idunidad</code>.
     */
    public final TableField<VMedidasRecord, Integer> IDUNIDAD = createField("idunidad", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_medidas.detalle</code>.
     */
    public final TableField<VMedidasRecord, String> DETALLE = createField("detalle", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.v_medidas.equivalencia</code>.
     */
    public final TableField<VMedidasRecord, Double> EQUIVALENCIA = createField("equivalencia", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_medidas.unidadpadre</code>.
     */
    public final TableField<VMedidasRecord, Integer> UNIDADPADRE = createField("unidadpadre", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_medidas.detallepadre</code>.
     */
    public final TableField<VMedidasRecord, String> DETALLEPADRE = createField("detallepadre", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.v_medidas.equivalenciapadre</code>.
     */
    public final TableField<VMedidasRecord, Double> EQUIVALENCIAPADRE = createField("equivalenciapadre", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>public.v_medidas</code> table reference
     */
    public VMedidas() {
        this("v_medidas", null);
    }

    /**
     * Create an aliased <code>public.v_medidas</code> table reference
     */
    public VMedidas(String alias) {
        this(alias, V_MEDIDAS);
    }

    private VMedidas(String alias, Table<VMedidasRecord> aliased) {
        this(alias, aliased, null);
    }

    private VMedidas(String alias, Table<VMedidasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMedidas as(String alias) {
        return new VMedidas(alias, this);
    }

    /**
     * Rename this table
     */
    public VMedidas rename(String name) {
        return new VMedidas(name, null);
    }
}
