/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Public;
import db.clases.tables.records.VPedidosRecord;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VPedidos extends TableImpl<VPedidosRecord> {

    private static final long serialVersionUID = 128684805;

    /**
     * The reference instance of <code>public.v_pedidos</code>
     */
    public static final VPedidos V_PEDIDOS = new VPedidos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VPedidosRecord> getRecordType() {
        return VPedidosRecord.class;
    }

    /**
     * The column <code>public.v_pedidos.idpedido</code>.
     */
    public final TableField<VPedidosRecord, Integer> IDPEDIDO = createField("idpedido", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_pedidos.numero</code>.
     */
    public final TableField<VPedidosRecord, String> NUMERO = createField("numero", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

    /**
     * The column <code>public.v_pedidos.fecha</code>.
     */
    public final TableField<VPedidosRecord, Date> FECHA = createField("fecha", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.v_pedidos.idcliente</code>.
     */
    public final TableField<VPedidosRecord, Integer> IDCLIENTE = createField("idcliente", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_pedidos.nombrecliente</code>.
     */
    public final TableField<VPedidosRecord, String> NOMBRECLIENTE = createField("nombrecliente", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_pedidos.direccion</code>.
     */
    public final TableField<VPedidosRecord, String> DIRECCION = createField("direccion", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_pedidos.telefono</code>.
     */
    public final TableField<VPedidosRecord, String> TELEFONO = createField("telefono", org.jooq.impl.SQLDataType.VARCHAR.length(9), this, "");

    /**
     * The column <code>public.v_pedidos.categoria</code>.
     */
    public final TableField<VPedidosRecord, String> CATEGORIA = createField("categoria", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_pedidos.pagado</code>.
     */
    public final TableField<VPedidosRecord, BigDecimal> PAGADO = createField("pagado", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.v_pedidos.debe</code>.
     */
    public final TableField<VPedidosRecord, BigDecimal> DEBE = createField("debe", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.v_pedidos.total</code>.
     */
    public final TableField<VPedidosRecord, BigDecimal> TOTAL = createField("total", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.v_pedidos.idempleado</code>.
     */
    public final TableField<VPedidosRecord, Integer> IDEMPLEADO = createField("idempleado", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_pedidos.nombreempleado</code>.
     */
    public final TableField<VPedidosRecord, String> NOMBREEMPLEADO = createField("nombreempleado", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_pedidos.estado</code>.
     */
    public final TableField<VPedidosRecord, String> ESTADO = createField("estado", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_pedidos.comentarios</code>.
     */
    public final TableField<VPedidosRecord, String> COMENTARIOS = createField("comentarios", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.v_pedidos</code> table reference
     */
    public VPedidos() {
        this("v_pedidos", null);
    }

    /**
     * Create an aliased <code>public.v_pedidos</code> table reference
     */
    public VPedidos(String alias) {
        this(alias, V_PEDIDOS);
    }

    private VPedidos(String alias, Table<VPedidosRecord> aliased) {
        this(alias, aliased, null);
    }

    private VPedidos(String alias, Table<VPedidosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidos as(String alias) {
        return new VPedidos(alias, this);
    }

    /**
     * Rename this table
     */
    public VPedidos rename(String name) {
        return new VPedidos(name, null);
    }
}
