/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Public;
import db.clases.tables.records.VProductosRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VProductos extends TableImpl<VProductosRecord> {

    private static final long serialVersionUID = -687026767;

    /**
     * The reference instance of <code>public.v_productos</code>
     */
    public static final VProductos V_PRODUCTOS = new VProductos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VProductosRecord> getRecordType() {
        return VProductosRecord.class;
    }

    /**
     * The column <code>public.v_productos.idproducto</code>.
     */
    public final TableField<VProductosRecord, Integer> IDPRODUCTO = createField("idproducto", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_productos.codigo</code>.
     */
    public final TableField<VProductosRecord, String> CODIGO = createField("codigo", org.jooq.impl.SQLDataType.VARCHAR.length(7), this, "");

    /**
     * The column <code>public.v_productos.nombre</code>.
     */
    public final TableField<VProductosRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_productos.detalle</code>.
     */
    public final TableField<VProductosRecord, String> DETALLE = createField("detalle", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_productos.color</code>.
     */
    public final TableField<VProductosRecord, String> COLOR = createField("color", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_productos.tiempofabrica</code>.
     */
    public final TableField<VProductosRecord, Integer> TIEMPOFABRICA = createField("tiempofabrica", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_productos.categoria</code>.
     */
    public final TableField<VProductosRecord, String> CATEGORIA = createField("categoria", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_productos.costo_administrativo</code>.
     */
    public final TableField<VProductosRecord, BigDecimal> COSTO_ADMINISTRATIVO = createField("costo_administrativo", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.v_productos.costo_inventario</code>.
     */
    public final TableField<VProductosRecord, BigDecimal> COSTO_INVENTARIO = createField("costo_inventario", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.v_productos.p_normal</code>.
     */
    public final TableField<VProductosRecord, BigDecimal> P_NORMAL = createField("p_normal", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.v_productos.p_vip</code>.
     */
    public final TableField<VProductosRecord, BigDecimal> P_VIP = createField("p_vip", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.v_productos.p_dist</code>.
     */
    public final TableField<VProductosRecord, BigDecimal> P_DIST = createField("p_dist", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * The column <code>public.v_productos.termina</code>.
     */
    public final TableField<VProductosRecord, String> TERMINA = createField("termina", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_productos.imagen</code>.
     */
    public final TableField<VProductosRecord, byte[]> IMAGEN = createField("imagen", org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.v_productos.baja</code>.
     */
    public final TableField<VProductosRecord, Boolean> BAJA = createField("baja", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>public.v_productos</code> table reference
     */
    public VProductos() {
        this("v_productos", null);
    }

    /**
     * Create an aliased <code>public.v_productos</code> table reference
     */
    public VProductos(String alias) {
        this(alias, V_PRODUCTOS);
    }

    private VProductos(String alias, Table<VProductosRecord> aliased) {
        this(alias, aliased, null);
    }

    private VProductos(String alias, Table<VProductosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProductos as(String alias) {
        return new VProductos(alias, this);
    }

    /**
     * Rename this table
     */
    public VProductos rename(String name) {
        return new VProductos(name, null);
    }
}
