/**
 * This class is generated by jOOQ
 */
package db.clases.tables;


import db.clases.Public;
import db.clases.tables.records.VVentasRecord;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VVentas extends TableImpl<VVentasRecord> {

    private static final long serialVersionUID = 1176894495;

    /**
     * The reference instance of <code>public.v_ventas</code>
     */
    public static final VVentas V_VENTAS = new VVentas();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VVentasRecord> getRecordType() {
        return VVentasRecord.class;
    }

    /**
     * The column <code>public.v_ventas.idventa</code>.
     */
    public final TableField<VVentasRecord, Integer> IDVENTA = createField("idventa", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_ventas.numerofactura</code>.
     */
    public final TableField<VVentasRecord, String> NUMEROFACTURA = createField("numerofactura", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_ventas.fecha</code>.
     */
    public final TableField<VVentasRecord, Date> FECHA = createField("fecha", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.v_ventas.idcliente</code>.
     */
    public final TableField<VVentasRecord, Integer> IDCLIENTE = createField("idcliente", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_ventas.nombre</code>.
     */
    public final TableField<VVentasRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_ventas.direccion</code>.
     */
    public final TableField<VVentasRecord, String> DIRECCION = createField("direccion", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_ventas.telefono</code>.
     */
    public final TableField<VVentasRecord, String> TELEFONO = createField("telefono", org.jooq.impl.SQLDataType.VARCHAR.length(9), this, "");

    /**
     * The column <code>public.v_ventas.tipo</code>.
     */
    public final TableField<VVentasRecord, String> TIPO = createField("tipo", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_ventas.tipodoc</code>.
     */
    public final TableField<VVentasRecord, String> TIPODOC = createField("tipodoc", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_ventas.total</code>.
     */
    public final TableField<VVentasRecord, BigDecimal> TOTAL = createField("total", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2), this, "");

    /**
     * Create a <code>public.v_ventas</code> table reference
     */
    public VVentas() {
        this("v_ventas", null);
    }

    /**
     * Create an aliased <code>public.v_ventas</code> table reference
     */
    public VVentas(String alias) {
        this(alias, V_VENTAS);
    }

    private VVentas(String alias, Table<VVentasRecord> aliased) {
        this(alias, aliased, null);
    }

    private VVentas(String alias, Table<VVentasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VVentas as(String alias) {
        return new VVentas(alias, this);
    }

    /**
     * Rename this table
     */
    public VVentas rename(String name) {
        return new VVentas(name, null);
    }
}
