/**
 * This class is generated by jOOQ
 */
package db.clases;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.caja_idcaja_seq</code>
     */
    public static final Sequence<Long> CAJA_IDCAJA_SEQ = new SequenceImpl<Long>("caja_idcaja_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.cargo_idcargo_seq</code>
     */
    public static final Sequence<Long> CARGO_IDCARGO_SEQ = new SequenceImpl<Long>("cargo_idcargo_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.categoria_cliente_idcategoria_seq</code>
     */
    public static final Sequence<Long> CATEGORIA_CLIENTE_IDCATEGORIA_SEQ = new SequenceImpl<Long>("categoria_cliente_idcategoria_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.categoria_inventario_idcategoria_seq</code>
     */
    public static final Sequence<Long> CATEGORIA_INVENTARIO_IDCATEGORIA_SEQ = new SequenceImpl<Long>("categoria_inventario_idcategoria_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.categoria_producto_idcategoria_seq</code>
     */
    public static final Sequence<Long> CATEGORIA_PRODUCTO_IDCATEGORIA_SEQ = new SequenceImpl<Long>("categoria_producto_idcategoria_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.cliente_idcliente_seq</code>
     */
    public static final Sequence<Long> CLIENTE_IDCLIENTE_SEQ = new SequenceImpl<Long>("cliente_idcliente_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.compras_idcompra_seq</code>
     */
    public static final Sequence<Long> COMPRAS_IDCOMPRA_SEQ = new SequenceImpl<Long>("compras_idcompra_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.contacto_cliente_idcontacto_seq</code>
     */
    public static final Sequence<Long> CONTACTO_CLIENTE_IDCONTACTO_SEQ = new SequenceImpl<Long>("contacto_cliente_idcontacto_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.contacto_proveedor_idcontacto_seq</code>
     */
    public static final Sequence<Long> CONTACTO_PROVEEDOR_IDCONTACTO_SEQ = new SequenceImpl<Long>("contacto_proveedor_idcontacto_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.cotizacion_idcotizacion_seq</code>
     */
    public static final Sequence<Long> COTIZACION_IDCOTIZACION_SEQ = new SequenceImpl<Long>("cotizacion_idcotizacion_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.empleado_idempleado_seq</code>
     */
    public static final Sequence<Long> EMPLEADO_IDEMPLEADO_SEQ = new SequenceImpl<Long>("empleado_idempleado_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.gastos_idgasto_seq</code>
     */
    public static final Sequence<Long> GASTOS_IDGASTO_SEQ = new SequenceImpl<Long>("gastos_idgasto_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.inventario_idinventario_seq</code>
     */
    public static final Sequence<Long> INVENTARIO_IDINVENTARIO_SEQ = new SequenceImpl<Long>("inventario_idinventario_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.medida_idmedida_seq</code>
     */
    public static final Sequence<Long> MEDIDA_IDMEDIDA_SEQ = new SequenceImpl<Long>("medida_idmedida_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.movimiento_caja_idmovimiento_seq</code>
     */
    public static final Sequence<Long> MOVIMIENTO_CAJA_IDMOVIMIENTO_SEQ = new SequenceImpl<Long>("movimiento_caja_idmovimiento_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.pedido_idpedido_seq</code>
     */
    public static final Sequence<Long> PEDIDO_IDPEDIDO_SEQ = new SequenceImpl<Long>("pedido_idpedido_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.permisos_idpermiso_seq</code>
     */
    public static final Sequence<Long> PERMISOS_IDPERMISO_SEQ = new SequenceImpl<Long>("permisos_idpermiso_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.precios_idprecio_seq</code>
     */
    public static final Sequence<Long> PRECIOS_IDPRECIO_SEQ = new SequenceImpl<Long>("precios_idprecio_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.producto_idproducto_seq</code>
     */
    public static final Sequence<Long> PRODUCTO_IDPRODUCTO_SEQ = new SequenceImpl<Long>("producto_idproducto_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.proveedor_idproveedor_seq</code>
     */
    public static final Sequence<Long> PROVEEDOR_IDPROVEEDOR_SEQ = new SequenceImpl<Long>("proveedor_idproveedor_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.rol_idrol_seq</code>
     */
    public static final Sequence<Long> ROL_IDROL_SEQ = new SequenceImpl<Long>("rol_idrol_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.tamanio_idtamanio_seq</code>
     */
    public static final Sequence<Long> TAMANIO_IDTAMANIO_SEQ = new SequenceImpl<Long>("tamanio_idtamanio_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.unidad_medida_idunidad_seq</code>
     */
    public static final Sequence<Long> UNIDAD_MEDIDA_IDUNIDAD_SEQ = new SequenceImpl<Long>("unidad_medida_idunidad_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.usuario_idusuario_seq</code>
     */
    public static final Sequence<Long> USUARIO_IDUSUARIO_SEQ = new SequenceImpl<Long>("usuario_idusuario_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.usuario_rol_idusuario_seq</code>
     */
    public static final Sequence<Long> USUARIO_ROL_IDUSUARIO_SEQ = new SequenceImpl<Long>("usuario_rol_idusuario_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.venta_idventa_seq</code>
     */
    public static final Sequence<Long> VENTA_IDVENTA_SEQ = new SequenceImpl<Long>("venta_idventa_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
