/**
 * This class is generated by jOOQ
 */
package db.clases.routines;


import db.clases.Public;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActualizarCostosProduccionEmpresa extends AbstractRoutine<Object> {

    private static final long serialVersionUID = -66660944;

    /**
     * The parameter <code>public.actualizar_costos_produccion_empresa.RETURN_VALUE</code>.
     */
    public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"), false, false);

    /**
     * Create a new routine call instance
     */
    public ActualizarCostosProduccionEmpresa() {
        super("actualizar_costos_produccion_empresa", Public.PUBLIC, org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"));

        setReturnParameter(RETURN_VALUE);
    }
}
