/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.Cargo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CargoRecord extends UpdatableRecordImpl<CargoRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -1905792044;

    /**
     * Setter for <code>public.cargo.idcargo</code>.
     */
    public void setIdcargo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.cargo.idcargo</code>.
     */
    public Integer getIdcargo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.cargo.cargo</code>.
     */
    public void setCargo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.cargo.cargo</code>.
     */
    public String getCargo() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Cargo.CARGO.IDCARGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Cargo.CARGO.CARGO_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcargo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCargo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CargoRecord value1(Integer value) {
        setIdcargo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CargoRecord value2(String value) {
        setCargo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CargoRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CargoRecord
     */
    public CargoRecord() {
        super(Cargo.CARGO);
    }

    /**
     * Create a detached, initialised CargoRecord
     */
    public CargoRecord(Integer idcargo, String cargo) {
        super(Cargo.CARGO);

        set(0, idcargo);
        set(1, cargo);
    }
}
