/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.CategoriaCliente;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoriaClienteRecord extends UpdatableRecordImpl<CategoriaClienteRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -1438506055;

    /**
     * Setter for <code>public.categoria_cliente.idcategoria</code>.
     */
    public void setIdcategoria(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.categoria_cliente.idcategoria</code>.
     */
    public Integer getIdcategoria() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.categoria_cliente.categoria</code>.
     */
    public void setCategoria(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.categoria_cliente.categoria</code>.
     */
    public String getCategoria() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CategoriaCliente.CATEGORIA_CLIENTE.IDCATEGORIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CategoriaCliente.CATEGORIA_CLIENTE.CATEGORIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcategoria();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoriaClienteRecord value1(Integer value) {
        setIdcategoria(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoriaClienteRecord value2(String value) {
        setCategoria(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoriaClienteRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoriaClienteRecord
     */
    public CategoriaClienteRecord() {
        super(CategoriaCliente.CATEGORIA_CLIENTE);
    }

    /**
     * Create a detached, initialised CategoriaClienteRecord
     */
    public CategoriaClienteRecord(Integer idcategoria, String categoria) {
        super(CategoriaCliente.CATEGORIA_CLIENTE);

        set(0, idcategoria);
        set(1, categoria);
    }
}
