/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.CategoriaInventario;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoriaInventarioRecord extends UpdatableRecordImpl<CategoriaInventarioRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1681615158;

    /**
     * Setter for <code>public.categoria_inventario.idcategoria</code>.
     */
    public void setIdcategoria(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.categoria_inventario.idcategoria</code>.
     */
    public Integer getIdcategoria() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.categoria_inventario.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.categoria_inventario.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.categoria_inventario.descripcion</code>.
     */
    public void setDescripcion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.categoria_inventario.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CategoriaInventario.CATEGORIA_INVENTARIO.IDCATEGORIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CategoriaInventario.CATEGORIA_INVENTARIO.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CategoriaInventario.CATEGORIA_INVENTARIO.DESCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcategoria();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoriaInventarioRecord value1(Integer value) {
        setIdcategoria(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoriaInventarioRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoriaInventarioRecord value3(String value) {
        setDescripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoriaInventarioRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoriaInventarioRecord
     */
    public CategoriaInventarioRecord() {
        super(CategoriaInventario.CATEGORIA_INVENTARIO);
    }

    /**
     * Create a detached, initialised CategoriaInventarioRecord
     */
    public CategoriaInventarioRecord(Integer idcategoria, String nombre, String descripcion) {
        super(CategoriaInventario.CATEGORIA_INVENTARIO);

        set(0, idcategoria);
        set(1, nombre);
        set(2, descripcion);
    }
}
