/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.Cliente;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClienteRecord extends UpdatableRecordImpl<ClienteRecord> implements Record13<Integer, String, String, String, String, String, String, String, String, String, String, Integer, Boolean> {

    private static final long serialVersionUID = 1571393280;

    /**
     * Setter for <code>public.cliente.idcliente</code>.
     */
    public void setIdcliente(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.cliente.idcliente</code>.
     */
    public Integer getIdcliente() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.cliente.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.cliente.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.cliente.direccion</code>.
     */
    public void setDireccion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.cliente.direccion</code>.
     */
    public String getDireccion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.cliente.telefono</code>.
     */
    public void setTelefono(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.cliente.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.cliente.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.cliente.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.cliente.tipo</code>.
     */
    public void setTipo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.cliente.tipo</code>.
     */
    public String getTipo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.cliente.giro</code>.
     */
    public void setGiro(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.cliente.giro</code>.
     */
    public String getGiro() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.cliente.iva</code>.
     */
    public void setIva(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.cliente.iva</code>.
     */
    public String getIva() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.cliente.nit</code>.
     */
    public void setNit(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.cliente.nit</code>.
     */
    public String getNit() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.cliente.registro</code>.
     */
    public void setRegistro(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.cliente.registro</code>.
     */
    public String getRegistro() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.cliente.representante</code>.
     */
    public void setRepresentante(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.cliente.representante</code>.
     */
    public String getRepresentante() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.cliente.idcategoria</code>.
     */
    public void setIdcategoria(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.cliente.idcategoria</code>.
     */
    public Integer getIdcategoria() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.cliente.baja</code>.
     */
    public void setBaja(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.cliente.baja</code>.
     */
    public Boolean getBaja() {
        return (Boolean) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, String, String, String, String, Integer, Boolean> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, String, String, String, String, Integer, Boolean> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Cliente.CLIENTE.IDCLIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Cliente.CLIENTE.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Cliente.CLIENTE.DIRECCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Cliente.CLIENTE.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Cliente.CLIENTE.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Cliente.CLIENTE.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Cliente.CLIENTE.GIRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Cliente.CLIENTE.IVA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Cliente.CLIENTE.NIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Cliente.CLIENTE.REGISTRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Cliente.CLIENTE.REPRESENTANTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return Cliente.CLIENTE.IDCATEGORIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field13() {
        return Cliente.CLIENTE.BAJA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcliente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getGiro();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getIva();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getNit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getRegistro();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getRepresentante();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getIdcategoria();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value13() {
        return getBaja();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value1(Integer value) {
        setIdcliente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value3(String value) {
        setDireccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value4(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value6(String value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value7(String value) {
        setGiro(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value8(String value) {
        setIva(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value9(String value) {
        setNit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value10(String value) {
        setRegistro(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value11(String value) {
        setRepresentante(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value12(Integer value) {
        setIdcategoria(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value13(Boolean value) {
        setBaja(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, Integer value12, Boolean value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClienteRecord
     */
    public ClienteRecord() {
        super(Cliente.CLIENTE);
    }

    /**
     * Create a detached, initialised ClienteRecord
     */
    public ClienteRecord(Integer idcliente, String nombre, String direccion, String telefono, String email, String tipo, String giro, String iva, String nit, String registro, String representante, Integer idcategoria, Boolean baja) {
        super(Cliente.CLIENTE);

        set(0, idcliente);
        set(1, nombre);
        set(2, direccion);
        set(3, telefono);
        set(4, email);
        set(5, tipo);
        set(6, giro);
        set(7, iva);
        set(8, nit);
        set(9, registro);
        set(10, representante);
        set(11, idcategoria);
        set(12, baja);
    }
}
