/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.Compras;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ComprasRecord extends UpdatableRecordImpl<ComprasRecord> implements Record6<Integer, Date, Integer, String, String, BigDecimal> {

    private static final long serialVersionUID = -1771291626;

    /**
     * Setter for <code>public.compras.idcompra</code>.
     */
    public void setIdcompra(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.compras.idcompra</code>.
     */
    public Integer getIdcompra() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.compras.fecha</code>.
     */
    public void setFecha(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.compras.fecha</code>.
     */
    public Date getFecha() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>public.compras.idproveedor</code>.
     */
    public void setIdproveedor(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.compras.idproveedor</code>.
     */
    public Integer getIdproveedor() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.compras.tipodocumento</code>.
     */
    public void setTipodocumento(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.compras.tipodocumento</code>.
     */
    public String getTipodocumento() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.compras.numerodocumento</code>.
     */
    public void setNumerodocumento(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.compras.numerodocumento</code>.
     */
    public String getNumerodocumento() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.compras.total</code>.
     */
    public void setTotal(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.compras.total</code>.
     */
    public BigDecimal getTotal() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Date, Integer, String, String, BigDecimal> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Date, Integer, String, String, BigDecimal> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Compras.COMPRAS.IDCOMPRA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return Compras.COMPRAS.FECHA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Compras.COMPRAS.IDPROVEEDOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Compras.COMPRAS.TIPODOCUMENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Compras.COMPRAS.NUMERODOCUMENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return Compras.COMPRAS.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcompra();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getFecha();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdproveedor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTipodocumento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNumerodocumento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ComprasRecord value1(Integer value) {
        setIdcompra(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ComprasRecord value2(Date value) {
        setFecha(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ComprasRecord value3(Integer value) {
        setIdproveedor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ComprasRecord value4(String value) {
        setTipodocumento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ComprasRecord value5(String value) {
        setNumerodocumento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ComprasRecord value6(BigDecimal value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ComprasRecord values(Integer value1, Date value2, Integer value3, String value4, String value5, BigDecimal value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ComprasRecord
     */
    public ComprasRecord() {
        super(Compras.COMPRAS);
    }

    /**
     * Create a detached, initialised ComprasRecord
     */
    public ComprasRecord(Integer idcompra, Date fecha, Integer idproveedor, String tipodocumento, String numerodocumento, BigDecimal total) {
        super(Compras.COMPRAS);

        set(0, idcompra);
        set(1, fecha);
        set(2, idproveedor);
        set(3, tipodocumento);
        set(4, numerodocumento);
        set(5, total);
    }
}
