/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.ContactoProveedor;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactoProveedorRecord extends UpdatableRecordImpl<ContactoProveedorRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = 673758962;

    /**
     * Setter for <code>public.contacto_proveedor.idcontacto</code>.
     */
    public void setIdcontacto(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.contacto_proveedor.idcontacto</code>.
     */
    public Integer getIdcontacto() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.contacto_proveedor.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.contacto_proveedor.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.contacto_proveedor.telefono</code>.
     */
    public void setTelefono(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.contacto_proveedor.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.contacto_proveedor.idproveedor</code>.
     */
    public void setIdproveedor(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.contacto_proveedor.idproveedor</code>.
     */
    public Integer getIdproveedor() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ContactoProveedor.CONTACTO_PROVEEDOR.IDCONTACTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ContactoProveedor.CONTACTO_PROVEEDOR.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ContactoProveedor.CONTACTO_PROVEEDOR.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ContactoProveedor.CONTACTO_PROVEEDOR.IDPROVEEDOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcontacto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdproveedor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactoProveedorRecord value1(Integer value) {
        setIdcontacto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactoProveedorRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactoProveedorRecord value3(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactoProveedorRecord value4(Integer value) {
        setIdproveedor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactoProveedorRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContactoProveedorRecord
     */
    public ContactoProveedorRecord() {
        super(ContactoProveedor.CONTACTO_PROVEEDOR);
    }

    /**
     * Create a detached, initialised ContactoProveedorRecord
     */
    public ContactoProveedorRecord(Integer idcontacto, String nombre, String telefono, Integer idproveedor) {
        super(ContactoProveedor.CONTACTO_PROVEEDOR);

        set(0, idcontacto);
        set(1, nombre);
        set(2, telefono);
        set(3, idproveedor);
    }
}
