/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.PagosCompras;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PagosComprasRecord extends TableRecordImpl<PagosComprasRecord> implements Record3<BigDecimal, Date, Integer> {

    private static final long serialVersionUID = 1378000433;

    /**
     * Setter for <code>public.pagos_compras.pago</code>.
     */
    public void setPago(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pagos_compras.pago</code>.
     */
    public BigDecimal getPago() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.pagos_compras.fecha</code>.
     */
    public void setFecha(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pagos_compras.fecha</code>.
     */
    public Date getFecha() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>public.pagos_compras.idcompra</code>.
     */
    public void setIdcompra(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pagos_compras.idcompra</code>.
     */
    public Integer getIdcompra() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<BigDecimal, Date, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<BigDecimal, Date, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return PagosCompras.PAGOS_COMPRAS.PAGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return PagosCompras.PAGOS_COMPRAS.FECHA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PagosCompras.PAGOS_COMPRAS.IDCOMPRA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getPago();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getFecha();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdcompra();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PagosComprasRecord value1(BigDecimal value) {
        setPago(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PagosComprasRecord value2(Date value) {
        setFecha(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PagosComprasRecord value3(Integer value) {
        setIdcompra(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PagosComprasRecord values(BigDecimal value1, Date value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PagosComprasRecord
     */
    public PagosComprasRecord() {
        super(PagosCompras.PAGOS_COMPRAS);
    }

    /**
     * Create a detached, initialised PagosComprasRecord
     */
    public PagosComprasRecord(BigDecimal pago, Date fecha, Integer idcompra) {
        super(PagosCompras.PAGOS_COMPRAS);

        set(0, pago);
        set(1, fecha);
        set(2, idcompra);
    }
}
