/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.PagosPedido;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PagosPedidoRecord extends TableRecordImpl<PagosPedidoRecord> implements Record3<BigDecimal, Date, Integer> {

    private static final long serialVersionUID = -1762468576;

    /**
     * Setter for <code>public.pagos_pedido.pago</code>.
     */
    public void setPago(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pagos_pedido.pago</code>.
     */
    public BigDecimal getPago() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.pagos_pedido.fecha</code>.
     */
    public void setFecha(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pagos_pedido.fecha</code>.
     */
    public Date getFecha() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>public.pagos_pedido.idpedido</code>.
     */
    public void setIdpedido(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pagos_pedido.idpedido</code>.
     */
    public Integer getIdpedido() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<BigDecimal, Date, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<BigDecimal, Date, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return PagosPedido.PAGOS_PEDIDO.PAGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return PagosPedido.PAGOS_PEDIDO.FECHA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PagosPedido.PAGOS_PEDIDO.IDPEDIDO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getPago();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getFecha();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdpedido();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PagosPedidoRecord value1(BigDecimal value) {
        setPago(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PagosPedidoRecord value2(Date value) {
        setFecha(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PagosPedidoRecord value3(Integer value) {
        setIdpedido(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PagosPedidoRecord values(BigDecimal value1, Date value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PagosPedidoRecord
     */
    public PagosPedidoRecord() {
        super(PagosPedido.PAGOS_PEDIDO);
    }

    /**
     * Create a detached, initialised PagosPedidoRecord
     */
    public PagosPedidoRecord(BigDecimal pago, Date fecha, Integer idpedido) {
        super(PagosPedido.PAGOS_PEDIDO);

        set(0, pago);
        set(1, fecha);
        set(2, idpedido);
    }
}
