/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.Pedido;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PedidoRecord extends UpdatableRecordImpl<PedidoRecord> implements Record8<Integer, String, Date, Integer, Integer, String, BigDecimal, String> {

    private static final long serialVersionUID = 509939917;

    /**
     * Setter for <code>public.pedido.idpedido</code>.
     */
    public void setIdpedido(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pedido.idpedido</code>.
     */
    public Integer getIdpedido() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.pedido.numero</code>.
     */
    public void setNumero(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pedido.numero</code>.
     */
    public String getNumero() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.pedido.fecha</code>.
     */
    public void setFecha(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pedido.fecha</code>.
     */
    public Date getFecha() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>public.pedido.idcliente</code>.
     */
    public void setIdcliente(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pedido.idcliente</code>.
     */
    public Integer getIdcliente() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.pedido.idempleado</code>.
     */
    public void setIdempleado(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pedido.idempleado</code>.
     */
    public Integer getIdempleado() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.pedido.estado</code>.
     */
    public void setEstado(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pedido.estado</code>.
     */
    public String getEstado() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.pedido.total</code>.
     */
    public void setTotal(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.pedido.total</code>.
     */
    public BigDecimal getTotal() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.pedido.comentarios</code>.
     */
    public void setComentarios(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.pedido.comentarios</code>.
     */
    public String getComentarios() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Date, Integer, Integer, String, BigDecimal, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Date, Integer, Integer, String, BigDecimal, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Pedido.PEDIDO.IDPEDIDO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Pedido.PEDIDO.NUMERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Pedido.PEDIDO.FECHA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Pedido.PEDIDO.IDCLIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Pedido.PEDIDO.IDEMPLEADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Pedido.PEDIDO.ESTADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return Pedido.PEDIDO.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Pedido.PEDIDO.COMENTARIOS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdpedido();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNumero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getFecha();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdcliente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIdempleado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEstado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getComentarios();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value1(Integer value) {
        setIdpedido(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value2(String value) {
        setNumero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value3(Date value) {
        setFecha(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value4(Integer value) {
        setIdcliente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value5(Integer value) {
        setIdempleado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value6(String value) {
        setEstado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value7(BigDecimal value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord value8(String value) {
        setComentarios(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PedidoRecord values(Integer value1, String value2, Date value3, Integer value4, Integer value5, String value6, BigDecimal value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PedidoRecord
     */
    public PedidoRecord() {
        super(Pedido.PEDIDO);
    }

    /**
     * Create a detached, initialised PedidoRecord
     */
    public PedidoRecord(Integer idpedido, String numero, Date fecha, Integer idcliente, Integer idempleado, String estado, BigDecimal total, String comentarios) {
        super(Pedido.PEDIDO);

        set(0, idpedido);
        set(1, numero);
        set(2, fecha);
        set(3, idcliente);
        set(4, idempleado);
        set(5, estado);
        set(6, total);
        set(7, comentarios);
    }
}
