/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.Receta;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecetaRecord extends TableRecordImpl<RecetaRecord> implements Record5<Double, Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -636659376;

    /**
     * Setter for <code>public.receta.descargo</code>.
     */
    public void setDescargo(Double value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.receta.descargo</code>.
     */
    public Double getDescargo() {
        return (Double) get(0);
    }

    /**
     * Setter for <code>public.receta.idunidad</code>.
     */
    public void setIdunidad(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.receta.idunidad</code>.
     */
    public Integer getIdunidad() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.receta.descontaren</code>.
     */
    public void setDescontaren(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.receta.descontaren</code>.
     */
    public String getDescontaren() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.receta.idproducto</code>.
     */
    public void setIdproducto(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.receta.idproducto</code>.
     */
    public Integer getIdproducto() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.receta.idinventario</code>.
     */
    public void setIdinventario(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.receta.idinventario</code>.
     */
    public Integer getIdinventario() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Double, Integer, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Double, Integer, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field1() {
        return Receta.RECETA.DESCARGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Receta.RECETA.IDUNIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Receta.RECETA.DESCONTAREN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Receta.RECETA.IDPRODUCTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Receta.RECETA.IDINVENTARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value1() {
        return getDescargo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdunidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescontaren();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdproducto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIdinventario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecetaRecord value1(Double value) {
        setDescargo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecetaRecord value2(Integer value) {
        setIdunidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecetaRecord value3(String value) {
        setDescontaren(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecetaRecord value4(Integer value) {
        setIdproducto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecetaRecord value5(Integer value) {
        setIdinventario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecetaRecord values(Double value1, Integer value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecetaRecord
     */
    public RecetaRecord() {
        super(Receta.RECETA);
    }

    /**
     * Create a detached, initialised RecetaRecord
     */
    public RecetaRecord(Double descargo, Integer idunidad, String descontaren, Integer idproducto, Integer idinventario) {
        super(Receta.RECETA);

        set(0, descargo);
        set(1, idunidad);
        set(2, descontaren);
        set(3, idproducto);
        set(4, idinventario);
    }
}
