/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.VCompras;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VComprasRecord extends TableRecordImpl<VComprasRecord> implements Record10<Integer, String, Date, String, String, BigDecimal, BigDecimal, BigDecimal, Boolean, Integer> {

    private static final long serialVersionUID = -1873836117;

    /**
     * Setter for <code>public.v_compras.idproveedor</code>.
     */
    public void setIdproveedor(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_compras.idproveedor</code>.
     */
    public Integer getIdproveedor() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_compras.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_compras.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_compras.fecha</code>.
     */
    public void setFecha(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_compras.fecha</code>.
     */
    public Date getFecha() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>public.v_compras.tipodocumento</code>.
     */
    public void setTipodocumento(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_compras.tipodocumento</code>.
     */
    public String getTipodocumento() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_compras.numerodocumento</code>.
     */
    public void setNumerodocumento(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_compras.numerodocumento</code>.
     */
    public String getNumerodocumento() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_compras.pagos</code>.
     */
    public void setPagos(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_compras.pagos</code>.
     */
    public BigDecimal getPagos() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.v_compras.pendiente</code>.
     */
    public void setPendiente(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_compras.pendiente</code>.
     */
    public BigDecimal getPendiente() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.v_compras.total</code>.
     */
    public void setTotal(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_compras.total</code>.
     */
    public BigDecimal getTotal() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>public.v_compras.pagado</code>.
     */
    public void setPagado(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_compras.pagado</code>.
     */
    public Boolean getPagado() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.v_compras.idcompra</code>.
     */
    public void setIdcompra(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_compras.idcompra</code>.
     */
    public Integer getIdcompra() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Date, String, String, BigDecimal, BigDecimal, BigDecimal, Boolean, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Date, String, String, BigDecimal, BigDecimal, BigDecimal, Boolean, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VCompras.V_COMPRAS.IDPROVEEDOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VCompras.V_COMPRAS.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return VCompras.V_COMPRAS.FECHA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VCompras.V_COMPRAS.TIPODOCUMENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VCompras.V_COMPRAS.NUMERODOCUMENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return VCompras.V_COMPRAS.PAGOS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return VCompras.V_COMPRAS.PENDIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return VCompras.V_COMPRAS.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return VCompras.V_COMPRAS.PAGADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return VCompras.V_COMPRAS.IDCOMPRA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdproveedor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getFecha();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTipodocumento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNumerodocumento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getPagos();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getPendiente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getPagado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getIdcompra();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VComprasRecord value1(Integer value) {
        setIdproveedor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VComprasRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VComprasRecord value3(Date value) {
        setFecha(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VComprasRecord value4(String value) {
        setTipodocumento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VComprasRecord value5(String value) {
        setNumerodocumento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VComprasRecord value6(BigDecimal value) {
        setPagos(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VComprasRecord value7(BigDecimal value) {
        setPendiente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VComprasRecord value8(BigDecimal value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VComprasRecord value9(Boolean value) {
        setPagado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VComprasRecord value10(Integer value) {
        setIdcompra(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VComprasRecord values(Integer value1, String value2, Date value3, String value4, String value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, Boolean value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VComprasRecord
     */
    public VComprasRecord() {
        super(VCompras.V_COMPRAS);
    }

    /**
     * Create a detached, initialised VComprasRecord
     */
    public VComprasRecord(Integer idproveedor, String nombre, Date fecha, String tipodocumento, String numerodocumento, BigDecimal pagos, BigDecimal pendiente, BigDecimal total, Boolean pagado, Integer idcompra) {
        super(VCompras.V_COMPRAS);

        set(0, idproveedor);
        set(1, nombre);
        set(2, fecha);
        set(3, tipodocumento);
        set(4, numerodocumento);
        set(5, pagos);
        set(6, pendiente);
        set(7, total);
        set(8, pagado);
        set(9, idcompra);
    }
}
