/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.VCostosEmpresa;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VCostosEmpresaRecord extends TableRecordImpl<VCostosEmpresaRecord> implements Record4<Integer, String, BigDecimal, Boolean> {

    private static final long serialVersionUID = -1511494846;

    /**
     * Setter for <code>public.v_costos_empresa.idgasto</code>.
     */
    public void setIdgasto(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_costos_empresa.idgasto</code>.
     */
    public Integer getIdgasto() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_costos_empresa.detalle</code>.
     */
    public void setDetalle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_costos_empresa.detalle</code>.
     */
    public String getDetalle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_costos_empresa.gasto</code>.
     */
    public void setGasto(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_costos_empresa.gasto</code>.
     */
    public BigDecimal getGasto() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.v_costos_empresa.aplica</code>.
     */
    public void setAplica(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_costos_empresa.aplica</code>.
     */
    public Boolean getAplica() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, BigDecimal, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, BigDecimal, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VCostosEmpresa.V_COSTOS_EMPRESA.IDGASTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VCostosEmpresa.V_COSTOS_EMPRESA.DETALLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return VCostosEmpresa.V_COSTOS_EMPRESA.GASTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return VCostosEmpresa.V_COSTOS_EMPRESA.APLICA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdgasto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDetalle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getGasto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getAplica();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCostosEmpresaRecord value1(Integer value) {
        setIdgasto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCostosEmpresaRecord value2(String value) {
        setDetalle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCostosEmpresaRecord value3(BigDecimal value) {
        setGasto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCostosEmpresaRecord value4(Boolean value) {
        setAplica(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCostosEmpresaRecord values(Integer value1, String value2, BigDecimal value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VCostosEmpresaRecord
     */
    public VCostosEmpresaRecord() {
        super(VCostosEmpresa.V_COSTOS_EMPRESA);
    }

    /**
     * Create a detached, initialised VCostosEmpresaRecord
     */
    public VCostosEmpresaRecord(Integer idgasto, String detalle, BigDecimal gasto, Boolean aplica) {
        super(VCostosEmpresa.V_COSTOS_EMPRESA);

        set(0, idgasto);
        set(1, detalle);
        set(2, gasto);
        set(3, aplica);
    }
}
