/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.VDetalleCotizacion;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VDetalleCotizacionRecord extends TableRecordImpl<VDetalleCotizacionRecord> implements Record13<Integer, String, Integer, String, String, Float, Float, Boolean, Float, BigDecimal, BigDecimal, String, Integer> {

    private static final long serialVersionUID = 891478453;

    /**
     * Setter for <code>public.v_detalle_cotizacion.idcotizacion</code>.
     */
    public void setIdcotizacion(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.idcotizacion</code>.
     */
    public Integer getIdcotizacion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.numero</code>.
     */
    public void setNumero(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.numero</code>.
     */
    public String getNumero() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.idproducto</code>.
     */
    public void setIdproducto(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.idproducto</code>.
     */
    public Integer getIdproducto() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.codigo</code>.
     */
    public void setCodigo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.codigo</code>.
     */
    public String getCodigo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.nombre</code>.
     */
    public void setNombre(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.nombre</code>.
     */
    public String getNombre() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.ancho</code>.
     */
    public void setAncho(Float value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.ancho</code>.
     */
    public Float getAncho() {
        return (Float) get(5);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.largo</code>.
     */
    public void setLargo(Float value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.largo</code>.
     */
    public Float getLargo() {
        return (Float) get(6);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.especial</code>.
     */
    public void setEspecial(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.especial</code>.
     */
    public Boolean getEspecial() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.cantidad</code>.
     */
    public void setCantidad(Float value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.cantidad</code>.
     */
    public Float getCantidad() {
        return (Float) get(8);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.precio</code>.
     */
    public void setPrecio(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.precio</code>.
     */
    public BigDecimal getPrecio() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.subtotal</code>.
     */
    public void setSubtotal(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.subtotal</code>.
     */
    public BigDecimal getSubtotal() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.tamanio</code>.
     */
    public void setTamanio(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.tamanio</code>.
     */
    public String getTamanio() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.v_detalle_cotizacion.idtamanio</code>.
     */
    public void setIdtamanio(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_detalle_cotizacion.idtamanio</code>.
     */
    public Integer getIdtamanio() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, Integer, String, String, Float, Float, Boolean, Float, BigDecimal, BigDecimal, String, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, Integer, String, String, Float, Float, Boolean, Float, BigDecimal, BigDecimal, String, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.IDCOTIZACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.NUMERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.IDPRODUCTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.CODIGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field6() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.ANCHO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field7() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.LARGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.ESPECIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field9() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.CANTIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.PRECIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.SUBTOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.TAMANIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return VDetalleCotizacion.V_DETALLE_COTIZACION.IDTAMANIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcotizacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNumero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdproducto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value6() {
        return getAncho();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value7() {
        return getLargo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getEspecial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value9() {
        return getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTamanio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getIdtamanio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value1(Integer value) {
        setIdcotizacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value2(String value) {
        setNumero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value3(Integer value) {
        setIdproducto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value4(String value) {
        setCodigo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value5(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value6(Float value) {
        setAncho(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value7(Float value) {
        setLargo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value8(Boolean value) {
        setEspecial(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value9(Float value) {
        setCantidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value10(BigDecimal value) {
        setPrecio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value11(BigDecimal value) {
        setSubtotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value12(String value) {
        setTamanio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord value13(Integer value) {
        setIdtamanio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VDetalleCotizacionRecord values(Integer value1, String value2, Integer value3, String value4, String value5, Float value6, Float value7, Boolean value8, Float value9, BigDecimal value10, BigDecimal value11, String value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VDetalleCotizacionRecord
     */
    public VDetalleCotizacionRecord() {
        super(VDetalleCotizacion.V_DETALLE_COTIZACION);
    }

    /**
     * Create a detached, initialised VDetalleCotizacionRecord
     */
    public VDetalleCotizacionRecord(Integer idcotizacion, String numero, Integer idproducto, String codigo, String nombre, Float ancho, Float largo, Boolean especial, Float cantidad, BigDecimal precio, BigDecimal subtotal, String tamanio, Integer idtamanio) {
        super(VDetalleCotizacion.V_DETALLE_COTIZACION);

        set(0, idcotizacion);
        set(1, numero);
        set(2, idproducto);
        set(3, codigo);
        set(4, nombre);
        set(5, ancho);
        set(6, largo);
        set(7, especial);
        set(8, cantidad);
        set(9, precio);
        set(10, subtotal);
        set(11, tamanio);
        set(12, idtamanio);
    }
}
