/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.VMipedido;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VMipedidoRecord extends TableRecordImpl<VMipedidoRecord> implements Record7<Integer, String, Date, String, Integer, String, String> {

    private static final long serialVersionUID = 935531254;

    /**
     * Setter for <code>public.v_mipedido.idpedido</code>.
     */
    public void setIdpedido(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_mipedido.idpedido</code>.
     */
    public Integer getIdpedido() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_mipedido.numero</code>.
     */
    public void setNumero(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_mipedido.numero</code>.
     */
    public String getNumero() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_mipedido.fecha</code>.
     */
    public void setFecha(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_mipedido.fecha</code>.
     */
    public Date getFecha() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>public.v_mipedido.comentarios</code>.
     */
    public void setComentarios(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_mipedido.comentarios</code>.
     */
    public String getComentarios() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_mipedido.idempleado</code>.
     */
    public void setIdempleado(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_mipedido.idempleado</code>.
     */
    public Integer getIdempleado() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.v_mipedido.nombre</code>.
     */
    public void setNombre(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_mipedido.nombre</code>.
     */
    public String getNombre() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_mipedido.estado</code>.
     */
    public void setEstado(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_mipedido.estado</code>.
     */
    public String getEstado() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Date, String, Integer, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Date, String, Integer, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VMipedido.V_MIPEDIDO.IDPEDIDO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VMipedido.V_MIPEDIDO.NUMERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return VMipedido.V_MIPEDIDO.FECHA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VMipedido.V_MIPEDIDO.COMENTARIOS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return VMipedido.V_MIPEDIDO.IDEMPLEADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VMipedido.V_MIPEDIDO.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VMipedido.V_MIPEDIDO.ESTADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdpedido();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNumero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getFecha();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getComentarios();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIdempleado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEstado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMipedidoRecord value1(Integer value) {
        setIdpedido(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMipedidoRecord value2(String value) {
        setNumero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMipedidoRecord value3(Date value) {
        setFecha(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMipedidoRecord value4(String value) {
        setComentarios(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMipedidoRecord value5(Integer value) {
        setIdempleado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMipedidoRecord value6(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMipedidoRecord value7(String value) {
        setEstado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMipedidoRecord values(Integer value1, String value2, Date value3, String value4, Integer value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VMipedidoRecord
     */
    public VMipedidoRecord() {
        super(VMipedido.V_MIPEDIDO);
    }

    /**
     * Create a detached, initialised VMipedidoRecord
     */
    public VMipedidoRecord(Integer idpedido, String numero, Date fecha, String comentarios, Integer idempleado, String nombre, String estado) {
        super(VMipedido.V_MIPEDIDO);

        set(0, idpedido);
        set(1, numero);
        set(2, fecha);
        set(3, comentarios);
        set(4, idempleado);
        set(5, nombre);
        set(6, estado);
    }
}
