/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.VPedidoVenta;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VPedidoVentaRecord extends TableRecordImpl<VPedidoVentaRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = -412842743;

    /**
     * Setter for <code>public.v_pedido_venta.idventa</code>.
     */
    public void setIdventa(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_pedido_venta.idventa</code>.
     */
    public Integer getIdventa() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_pedido_venta.idpedido</code>.
     */
    public void setIdpedido(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_pedido_venta.idpedido</code>.
     */
    public Integer getIdpedido() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.v_pedido_venta.texto</code>.
     */
    public void setTexto(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_pedido_venta.texto</code>.
     */
    public String getTexto() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VPedidoVenta.V_PEDIDO_VENTA.IDVENTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return VPedidoVenta.V_PEDIDO_VENTA.IDPEDIDO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VPedidoVenta.V_PEDIDO_VENTA.TEXTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdventa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdpedido();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTexto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoVentaRecord value1(Integer value) {
        setIdventa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoVentaRecord value2(Integer value) {
        setIdpedido(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoVentaRecord value3(String value) {
        setTexto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoVentaRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VPedidoVentaRecord
     */
    public VPedidoVentaRecord() {
        super(VPedidoVenta.V_PEDIDO_VENTA);
    }

    /**
     * Create a detached, initialised VPedidoVentaRecord
     */
    public VPedidoVentaRecord(Integer idventa, Integer idpedido, String texto) {
        super(VPedidoVenta.V_PEDIDO_VENTA);

        set(0, idventa);
        set(1, idpedido);
        set(2, texto);
    }
}
