/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.VPedido;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VPedidoRecord extends TableRecordImpl<VPedidoRecord> implements Record15<Integer, String, Date, Integer, String, String, String, String, BigDecimal, BigDecimal, BigDecimal, Integer, String, String, String> {

    private static final long serialVersionUID = 1319188915;

    /**
     * Setter for <code>public.v_pedido.idpedido</code>.
     */
    public void setIdpedido(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_pedido.idpedido</code>.
     */
    public Integer getIdpedido() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_pedido.numero</code>.
     */
    public void setNumero(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_pedido.numero</code>.
     */
    public String getNumero() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_pedido.fecha</code>.
     */
    public void setFecha(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_pedido.fecha</code>.
     */
    public Date getFecha() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>public.v_pedido.idcliente</code>.
     */
    public void setIdcliente(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_pedido.idcliente</code>.
     */
    public Integer getIdcliente() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.v_pedido.nombrecliente</code>.
     */
    public void setNombrecliente(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_pedido.nombrecliente</code>.
     */
    public String getNombrecliente() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_pedido.direccion</code>.
     */
    public void setDireccion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_pedido.direccion</code>.
     */
    public String getDireccion() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_pedido.telefono</code>.
     */
    public void setTelefono(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_pedido.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_pedido.categoria</code>.
     */
    public void setCategoria(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_pedido.categoria</code>.
     */
    public String getCategoria() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_pedido.pagado</code>.
     */
    public void setPagado(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_pedido.pagado</code>.
     */
    public BigDecimal getPagado() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.v_pedido.debe</code>.
     */
    public void setDebe(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_pedido.debe</code>.
     */
    public BigDecimal getDebe() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.v_pedido.total</code>.
     */
    public void setTotal(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_pedido.total</code>.
     */
    public BigDecimal getTotal() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.v_pedido.idempleado</code>.
     */
    public void setIdempleado(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_pedido.idempleado</code>.
     */
    public Integer getIdempleado() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.v_pedido.nombreempleado</code>.
     */
    public void setNombreempleado(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_pedido.nombreempleado</code>.
     */
    public String getNombreempleado() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.v_pedido.estado</code>.
     */
    public void setEstado(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_pedido.estado</code>.
     */
    public String getEstado() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.v_pedido.comentarios</code>.
     */
    public void setComentarios(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_pedido.comentarios</code>.
     */
    public String getComentarios() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, Date, Integer, String, String, String, String, BigDecimal, BigDecimal, BigDecimal, Integer, String, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, Date, Integer, String, String, String, String, BigDecimal, BigDecimal, BigDecimal, Integer, String, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VPedido.V_PEDIDO.IDPEDIDO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VPedido.V_PEDIDO.NUMERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return VPedido.V_PEDIDO.FECHA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return VPedido.V_PEDIDO.IDCLIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VPedido.V_PEDIDO.NOMBRECLIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VPedido.V_PEDIDO.DIRECCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VPedido.V_PEDIDO.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return VPedido.V_PEDIDO.CATEGORIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return VPedido.V_PEDIDO.PAGADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return VPedido.V_PEDIDO.DEBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return VPedido.V_PEDIDO.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return VPedido.V_PEDIDO.IDEMPLEADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return VPedido.V_PEDIDO.NOMBREEMPLEADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return VPedido.V_PEDIDO.ESTADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return VPedido.V_PEDIDO.COMENTARIOS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdpedido();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNumero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getFecha();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdcliente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNombrecliente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getPagado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getDebe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getIdempleado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getNombreempleado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getEstado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getComentarios();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value1(Integer value) {
        setIdpedido(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value2(String value) {
        setNumero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value3(Date value) {
        setFecha(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value4(Integer value) {
        setIdcliente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value5(String value) {
        setNombrecliente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value6(String value) {
        setDireccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value7(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value8(String value) {
        setCategoria(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value9(BigDecimal value) {
        setPagado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value10(BigDecimal value) {
        setDebe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value11(BigDecimal value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value12(Integer value) {
        setIdempleado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value13(String value) {
        setNombreempleado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value14(String value) {
        setEstado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord value15(String value) {
        setComentarios(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPedidoRecord values(Integer value1, String value2, Date value3, Integer value4, String value5, String value6, String value7, String value8, BigDecimal value9, BigDecimal value10, BigDecimal value11, Integer value12, String value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VPedidoRecord
     */
    public VPedidoRecord() {
        super(VPedido.V_PEDIDO);
    }

    /**
     * Create a detached, initialised VPedidoRecord
     */
    public VPedidoRecord(Integer idpedido, String numero, Date fecha, Integer idcliente, String nombrecliente, String direccion, String telefono, String categoria, BigDecimal pagado, BigDecimal debe, BigDecimal total, Integer idempleado, String nombreempleado, String estado, String comentarios) {
        super(VPedido.V_PEDIDO);

        set(0, idpedido);
        set(1, numero);
        set(2, fecha);
        set(3, idcliente);
        set(4, nombrecliente);
        set(5, direccion);
        set(6, telefono);
        set(7, categoria);
        set(8, pagado);
        set(9, debe);
        set(10, total);
        set(11, idempleado);
        set(12, nombreempleado);
        set(13, estado);
        set(14, comentarios);
    }
}
