/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.VPrecios;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VPreciosRecord extends TableRecordImpl<VPreciosRecord> implements Record4<Integer, Integer, String, BigDecimal> {

    private static final long serialVersionUID = -686979011;

    /**
     * Setter for <code>public.v_precios.idprecio</code>.
     */
    public void setIdprecio(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_precios.idprecio</code>.
     */
    public Integer getIdprecio() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_precios.idproducto</code>.
     */
    public void setIdproducto(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_precios.idproducto</code>.
     */
    public Integer getIdproducto() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.v_precios.categoria</code>.
     */
    public void setCategoria(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_precios.categoria</code>.
     */
    public String getCategoria() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_precios.precio</code>.
     */
    public void setPrecio(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_precios.precio</code>.
     */
    public BigDecimal getPrecio() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VPrecios.V_PRECIOS.IDPRECIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return VPrecios.V_PRECIOS.IDPRODUCTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VPrecios.V_PRECIOS.CATEGORIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return VPrecios.V_PRECIOS.PRECIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdprecio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdproducto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPreciosRecord value1(Integer value) {
        setIdprecio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPreciosRecord value2(Integer value) {
        setIdproducto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPreciosRecord value3(String value) {
        setCategoria(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPreciosRecord value4(BigDecimal value) {
        setPrecio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPreciosRecord values(Integer value1, Integer value2, String value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VPreciosRecord
     */
    public VPreciosRecord() {
        super(VPrecios.V_PRECIOS);
    }

    /**
     * Create a detached, initialised VPreciosRecord
     */
    public VPreciosRecord(Integer idprecio, Integer idproducto, String categoria, BigDecimal precio) {
        super(VPrecios.V_PRECIOS);

        set(0, idprecio);
        set(1, idproducto);
        set(2, categoria);
        set(3, precio);
    }
}
