/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.VUsuarioEmpleado;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VUsuarioEmpleadoRecord extends TableRecordImpl<VUsuarioEmpleadoRecord> implements Record7<Integer, String, String, Integer, String, String, Boolean> {

    private static final long serialVersionUID = 1137822706;

    /**
     * Setter for <code>public.v_usuario_empleado.idempleado</code>.
     */
    public void setIdempleado(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_usuario_empleado.idempleado</code>.
     */
    public Integer getIdempleado() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_usuario_empleado.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_usuario_empleado.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_usuario_empleado.cargo</code>.
     */
    public void setCargo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_usuario_empleado.cargo</code>.
     */
    public String getCargo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_usuario_empleado.idusuario</code>.
     */
    public void setIdusuario(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_usuario_empleado.idusuario</code>.
     */
    public Integer getIdusuario() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.v_usuario_empleado.usuario</code>.
     */
    public void setUsuario(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_usuario_empleado.usuario</code>.
     */
    public String getUsuario() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_usuario_empleado.pass</code>.
     */
    public void setPass(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_usuario_empleado.pass</code>.
     */
    public String getPass() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_usuario_empleado.baja</code>.
     */
    public void setBaja(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_usuario_empleado.baja</code>.
     */
    public Boolean getBaja() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, String, String, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, String, String, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VUsuarioEmpleado.V_USUARIO_EMPLEADO.IDEMPLEADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VUsuarioEmpleado.V_USUARIO_EMPLEADO.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VUsuarioEmpleado.V_USUARIO_EMPLEADO.CARGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return VUsuarioEmpleado.V_USUARIO_EMPLEADO.IDUSUARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VUsuarioEmpleado.V_USUARIO_EMPLEADO.USUARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VUsuarioEmpleado.V_USUARIO_EMPLEADO.PASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return VUsuarioEmpleado.V_USUARIO_EMPLEADO.BAJA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdempleado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCargo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getBaja();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VUsuarioEmpleadoRecord value1(Integer value) {
        setIdempleado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VUsuarioEmpleadoRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VUsuarioEmpleadoRecord value3(String value) {
        setCargo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VUsuarioEmpleadoRecord value4(Integer value) {
        setIdusuario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VUsuarioEmpleadoRecord value5(String value) {
        setUsuario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VUsuarioEmpleadoRecord value6(String value) {
        setPass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VUsuarioEmpleadoRecord value7(Boolean value) {
        setBaja(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VUsuarioEmpleadoRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VUsuarioEmpleadoRecord
     */
    public VUsuarioEmpleadoRecord() {
        super(VUsuarioEmpleado.V_USUARIO_EMPLEADO);
    }

    /**
     * Create a detached, initialised VUsuarioEmpleadoRecord
     */
    public VUsuarioEmpleadoRecord(Integer idempleado, String nombre, String cargo, Integer idusuario, String usuario, String pass, Boolean baja) {
        super(VUsuarioEmpleado.V_USUARIO_EMPLEADO);

        set(0, idempleado);
        set(1, nombre);
        set(2, cargo);
        set(3, idusuario);
        set(4, usuario);
        set(5, pass);
        set(6, baja);
    }
}
