/**
 * This class is generated by jOOQ
 */
package db.clases.tables.records;


import db.clases.tables.VVentas;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VVentasRecord extends TableRecordImpl<VVentasRecord> implements Record10<Integer, String, Date, Integer, String, String, String, String, String, BigDecimal> {

    private static final long serialVersionUID = -1843291410;

    /**
     * Setter for <code>public.v_ventas.idventa</code>.
     */
    public void setIdventa(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_ventas.idventa</code>.
     */
    public Integer getIdventa() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_ventas.numerofactura</code>.
     */
    public void setNumerofactura(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_ventas.numerofactura</code>.
     */
    public String getNumerofactura() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_ventas.fecha</code>.
     */
    public void setFecha(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_ventas.fecha</code>.
     */
    public Date getFecha() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>public.v_ventas.idcliente</code>.
     */
    public void setIdcliente(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_ventas.idcliente</code>.
     */
    public Integer getIdcliente() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.v_ventas.nombre</code>.
     */
    public void setNombre(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_ventas.nombre</code>.
     */
    public String getNombre() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_ventas.direccion</code>.
     */
    public void setDireccion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_ventas.direccion</code>.
     */
    public String getDireccion() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_ventas.telefono</code>.
     */
    public void setTelefono(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_ventas.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_ventas.tipo</code>.
     */
    public void setTipo(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_ventas.tipo</code>.
     */
    public String getTipo() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_ventas.tipodoc</code>.
     */
    public void setTipodoc(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_ventas.tipodoc</code>.
     */
    public String getTipodoc() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.v_ventas.total</code>.
     */
    public void setTotal(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_ventas.total</code>.
     */
    public BigDecimal getTotal() {
        return (BigDecimal) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Date, Integer, String, String, String, String, String, BigDecimal> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Date, Integer, String, String, String, String, String, BigDecimal> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VVentas.V_VENTAS.IDVENTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VVentas.V_VENTAS.NUMEROFACTURA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return VVentas.V_VENTAS.FECHA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return VVentas.V_VENTAS.IDCLIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VVentas.V_VENTAS.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VVentas.V_VENTAS.DIRECCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VVentas.V_VENTAS.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return VVentas.V_VENTAS.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return VVentas.V_VENTAS.TIPODOC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return VVentas.V_VENTAS.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdventa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNumerofactura();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getFecha();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdcliente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getTipodoc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VVentasRecord value1(Integer value) {
        setIdventa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VVentasRecord value2(String value) {
        setNumerofactura(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VVentasRecord value3(Date value) {
        setFecha(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VVentasRecord value4(Integer value) {
        setIdcliente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VVentasRecord value5(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VVentasRecord value6(String value) {
        setDireccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VVentasRecord value7(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VVentasRecord value8(String value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VVentasRecord value9(String value) {
        setTipodoc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VVentasRecord value10(BigDecimal value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VVentasRecord values(Integer value1, String value2, Date value3, Integer value4, String value5, String value6, String value7, String value8, String value9, BigDecimal value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VVentasRecord
     */
    public VVentasRecord() {
        super(VVentas.V_VENTAS);
    }

    /**
     * Create a detached, initialised VVentasRecord
     */
    public VVentasRecord(Integer idventa, String numerofactura, Date fecha, Integer idcliente, String nombre, String direccion, String telefono, String tipo, String tipodoc, BigDecimal total) {
        super(VVentas.V_VENTAS);

        set(0, idventa);
        set(1, numerofactura);
        set(2, fecha);
        set(3, idcliente);
        set(4, nombre);
        set(5, direccion);
        set(6, telefono);
        set(7, tipo);
        set(8, tipodoc);
        set(9, total);
    }
}
